#! /usr/bin/env node

/**
 * @file git pre-commit hook git代码提交之前对文件进行检查
 * @author cxtom <cxtom2010@gmail.com>
 */

var exec = require('child_process').exec;
var fs   = require('fs');
var path = require('path');

var IGNORE_FILENAME = '.fecsignore';
var name = 'fecs-git-precommit-check';

var fecs;
var minimatch;

console.log('要提交代码先要通过fecs审查哦！\n');
// console.log('检查是否已经安装fecs');

exec('npm root -g', function (error, result, stderr) {

    if (error !== null) {
        console.log('exec error: ' + error);
        process.exit(1);
    }

    console.time(name);

    var fecsRoot = result.trim() + '/fecs';
    try {
        require(fecsRoot);
    }
    catch (e) {
        console.log('还没有安装fecs，请先运行\'npm install fecs -g\'~~');
        process.exit(1);
    }

    fecs = require(fecsRoot);
    minimatch = require(fecsRoot + '/node_modules/minimatch');

    // console.log('开始检查...');

    var stagedFiles;

    exec('git diff-index --cached --name-only HEAD', function (error, result, stderr) {
        if (error !== null) {
            console.log('' + error);

            if (('' + error).indexOf('unknown revision') > 0) {
                console.log('仓库还没有提交记录，默认对所有文件进行检查');
                stagedFiles = ['./**/*.{js,css,less,html}']
            }
            else {
                process.exit(1);
            }
        }
        // 还有文件未添加
        if (result.indexOf('Changes not staged for commit:') >= 0) {
            console.log(result);
            process.exit(1);
        }

        console.log('提交的文件列表：');
        // if (!!stagedFiles) {
        //     console.log('./**/*.{js,css,less,html}');
        // }
        // else {
        //     console.log(result);
        // }

        console.log(result);

        stagedFiles = stagedFiles || result.trim().split('\n');

        if (!stagedFiles || !stagedFiles.length) {
            process.exit(0);
            return;
        }

        stagedFiles = ignore(stagedFiles);

        if (stagedFiles.length === 0) {
            console.log('No file need to be checked~');
        }
        else {
            fecsCheck(stagedFiles);
        }
    });
});


/**
 * 删除fecs中忽略的文件
 * @param  {Array} files 文件列表
 * @return {Array}       修改后的文件列表
 */
function ignore(files) {
    var patterns = [];
    function valid(line) {
        line = line.trim();
        return line !== '' && line[0] !== '#';
    }
    var ignoreFilePath = path.resolve(__dirname, '../../' + IGNORE_FILENAME);

    try {
        patterns = fs.readFileSync(ignoreFilePath, 'utf8').split(/\r?\n/).filter(valid);
        files = files.filter(function (filePath) {
            var result = false;
            patterns.forEach(function (pattern) {
                var matches = minimatch(filePath, pattern) || minimatch(filePath, pattern + '/**');
                if (matches) {
                    result = true;
                    console.log('%s is ignored by %s.', filePath, '.fecsignore');
                    return false;
                }
            });
            return !result;
        });
    }
    catch (e) {
        // 没有.fecsignore
    }
    console.log('');
    return files;
}

/**
 * 运行代码检查
 * @param  {Array} files 文件列表数组
 */
function fecsCheck(files) {

    var options= {
        color: true,
        _: files
    }

    var done = function (success, json) {
        console.timeEnd(name);
        if(!success) {
            console.log('看来规范还有问题，请修改以后再提交吧！');
        }
        console.log('');
        process.exit(success ? 0 : 1);
    };

    fecs.check(options, done);
}
