#! /usr/bin/env node

/**
 * @file git pre-commit hook git代码提交之前对文件进行检查
 * @author chenxiao07@baidu.com
 */

var path        = require('path');
var exec        = require('child_process').exec;

var fs;
var ignored;
var jschecker;
var csschecker;
var lesschecker;
var htmlchecker;

console.log('要提交代码先要通过fecs审查哦！\n');
console.log('检查是否已经安装fecs');

exec('npm root -g', function (error, result, stderr) {

    if (error !== null) {
        console.log('exec error: ' + error);
        process.exit(1);
    }

    var fecsRoot = result.trim() + '/fecs';
    try {
        require(fecsRoot);
    }
    catch (e) {
        console.log('还没有安装fecs，请先运行\'npm install fecs -g\'~~');
        process.exit(1);
    }

    fs          = require(fecsRoot + '/node_modules/vinyl-fs');
    ignored     = require(fecsRoot + '/lib/ignored');
    jschecker   = require(fecsRoot + '/lib/js/checker');
    csschecker  = require(fecsRoot + '/lib/css/checker');
    lesschecker = require(fecsRoot + '/lib/less/checker');
    htmlchecker = require(fecsRoot + '/lib/html/checker');

    console.log('开始检查...');

    var stagedFiles;

    exec('git diff-index --cached --name-only HEAD', function (error, result, stderr) {
        if (error !== null) {
            console.log('' + error);

            if (('' + error).indexOf('unknown revision') > 0) {
                console.log('仓库还没有提交记录，默认对所有文件进行检查');
                stagedFiles = ['./**/*.{js,css,less,html}']
            }
            else {
                process.exit(1);
            }
        }
        // 还有文件未添加
        if (result.indexOf('Changes not staged for commit:') >= 0) {
            console.log(result);
            process.exit(1);
        }

        console.log('提交的文件列表：');
        if (!!stagedFiles) {
            console.log('./**/*.{js,css,less,html}');
        }
        else {
            console.log(result);
        }

        console.log(result);

        stagedFiles = stagedFiles || result.trim().split('\n');

        if (!stagedFiles || !stagedFiles.length) {
            process.exit(0);
            return;
        }

        fecsCheck(stagedFiles);
    });
});



/**
 * 执行对文件内容的检查
 *
 */
function filesCheck (files, options) {
    var specials = [];
    return fs.src(files, {cwdbase: true})
        .pipe(ignored(options, specials))
        .pipe(jschecker.exec(options))
        .pipe(csschecker.exec(options))
        .pipe(lesschecker.exec(options))
        .pipe(htmlchecker.exec(options));
}

function fecsCheck(files) {

    var name = 'fecs-git-precommit-check';

    console.time(name);

    var options= {
        color: true
    }

    var log = require('fecs/lib/log')(options.color);
    var reporter = require('fecs/lib/reporter').get(log, options);

    done = function (success, json) {
        console.timeEnd(name);
        if(!success) {
            console.log('看来规范还有问题，请修改以后再提交吧！');
        }
        process.exit(success ? 0 : 1);
    };

    return filesCheck(files, options)
        .pipe(reporter)
        .once('end', done);
}
